/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MicroLcHeaders } from "./components/nofication-center/micro-lc-notification-center.types";
export namespace Components {
    interface MicroLcNotificationCenter {
        "endpoint": string;
        "headers": MicroLcHeaders;
        "limit": number;
    }
}
declare global {
    interface HTMLMicroLcNotificationCenterElement extends Components.MicroLcNotificationCenter, HTMLStencilElement {
    }
    var HTMLMicroLcNotificationCenterElement: {
        prototype: HTMLMicroLcNotificationCenterElement;
        new (): HTMLMicroLcNotificationCenterElement;
    };
    interface HTMLElementTagNameMap {
        "micro-lc-notification-center": HTMLMicroLcNotificationCenterElement;
    }
}
declare namespace LocalJSX {
    interface MicroLcNotificationCenter {
        "endpoint"?: string;
        "headers"?: MicroLcHeaders;
        "limit"?: number;
    }
    interface IntrinsicElements {
        "micro-lc-notification-center": MicroLcNotificationCenter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "micro-lc-notification-center": LocalJSX.MicroLcNotificationCenter & JSXBase.HTMLAttributes<HTMLMicroLcNotificationCenterElement>;
        }
    }
}
